framework:
    cache:
        # Unique namespace seed to avoid key collisions across projects
        prefix_seed: 'redis_demo_app'
        default_redis_provider: '%env(CACHE_DSN)%'

        # Dedicated Redis-backed pool for your app data
        pools:
            cache.task:
                adapter: cache.adapter.redis
