framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    cache:
        default_redis_provider: '%env(CACHE_DSN)%'
        pools:
            cache.task:
                adapter: cache.adapter.redis


    session:
        handler_id: session.handler.redis
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
