parameters:
    redis_dsn: '%env(CACHE_DSN)%'

services:
    redis:
        class: Predis\Client
        arguments:
            - '%redis_dsn%'

    session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@redis'
            - { prefix: 'sess_', ttl: 1800 } # adjust as you like
