parameters:
    redis_dsn: '%env(CACHE_DSN)%'

services:
    # Generic Redis connection ( if available "phpredis"; falls back to Predis)
    .redis_connection:
        class: Redis|Predis\Client
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments: ['%redis_dsn%']

    session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@.redis_connection'
            - { prefix: 'sess_', ttl: 1800 } # 30 min
