services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_symfony
    container_name: app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - database
    volumes:
      - .:/var/www/html

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data: